language: python
python:
- '2.7'
- '3.0'
install:
- pip install -r requirements.txt
- pip install coveralls

notifications:
  email:
    on_failure: never

services:
- postgresql

before_script:
- psql -c "CREATE USER admin WITH PASSWORD 'admin';" -U postgres
- psql -c "CREATE DATABASE bucketlist;" -U postgres
- psql -c "CREATE DATABASE test_bucketlist;" -U postgres
- psql -c "GRANT ALL PRIVILEGES ON DATABASE bucketlist to admin;" -U postgres
- psql -c "GRANT ALL PRIVILEGES ON DATABASE test_bucketlist to admin;" -U postgres

- python manage.py dropdb
- python manage.py drop_test_db
- python manage.py initdb
- python manage.py populatedb

script: nosetests --with-coverage --cover-package=bucketlist

after_success: coveralls